services:
  gov-bp:
    platform: linux/amd64
    image: ubuntu:22.04
    container_name: gov-bp
    working_dir: /setup
    command: >
      bash -c "apt-get update -qq &&
      apt-get install -y wget ca-certificates libcurl4 &&
      wget -q https://github.com/AntelopeIO/spring/releases/download/v1.1.3/antelope-spring_1.1.3_amd64.deb &&
      apt-get install -y ./antelope-spring_1.1.3_amd64.deb &&
      mkdir -p /chain/config /chain/data &&
      nodeos --config-dir /chain/config --data-dir /chain/data --enable-stale-production"
    volumes:
      - ./gov:/chain
      - ./contracts:/setup/contracts
    ports:
      - "8888:8888"
      - "9876:9876"

  bank-read:
    platform: linux/amd64
    image: ubuntu:22.04
    container_name: bank-read
    working_dir: /setup
    command: >
      bash -c "apt-get update -qq &&
      apt-get install -y wget ca-certificates libcurl4 &&
      wget -q https://github.com/AntelopeIO/spring/releases/download/v1.1.3/antelope-spring_1.1.3_amd64.deb &&
      apt-get install -y ./antelope-spring_1.1.3_amd64.deb &&
      mkdir -p /chain/config /chain/data &&
      nodeos --config-dir /chain/config --data-dir /chain/data --read-mode=head --p2p-accept-transactions=false --api-accept-transactions=false --http-server-address=0.0.0.0:8889 --p2p-peer-address=gov-bp:9876"
    depends_on:
      - gov-bp
    volumes:
      - ./bank:/chain
    ports:
      - "8889:8889"

  cdt-builder:
    platform: linux/amd64
    image: ubuntu:22.04
    container_name: cdt-builder
    working_dir: /workspace
    command: >
      /bin/bash -c "
      apt-get update -qq &&
      apt-get install -y wget build-essential clang cmake libxml2-dev python3 python3-pip git &&
      wget https://github.com/AntelopeIO/cdt/releases/download/v4.1.0/cdt_4.1.0-1_amd64.deb &&
      apt-get install -y ./cdt_4.1.0-1_amd64.deb &&
      tail -f /dev/null
      "
    volumes:
      - ./contracts:/workspace/contracts
